import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('electron', {
  git: {
    status:    (path: string)                               => ipcRenderer.invoke('git:status', path),
    log:       (path: string, limit?: number)               => ipcRenderer.invoke('git:log', path, limit),
    stage:     (path: string, files: string[])              => ipcRenderer.invoke('git:stage', path, files),
    stageAll:  (path: string)                               => ipcRenderer.invoke('git:stageAll', path),
    unstage:   (path: string, files: string[])              => ipcRenderer.invoke('git:unstage', path, files),
    commit:    (path: string, message: string)              => ipcRenderer.invoke('git:commit', path, message),
    push:      (path: string)                               => ipcRenderer.invoke('git:push', path),
    pull:      (path: string, strategy?: string)             => ipcRenderer.invoke('git:pull', path, strategy),
    branches:  (path: string)                               => ipcRenderer.invoke('git:branches', path),
    checkout:  (path: string, branch: string)               => ipcRenderer.invoke('git:checkout', path, branch),
    diff:      (path: string, file: string, staged?: boolean) => ipcRenderer.invoke('git:diff', path, file, staged),
    isRepo:       (path: string)                             => ipcRenderer.invoke('git:isRepo', path),
    showCommit:   (path: string, hash: string)               => ipcRenderer.invoke('git:showCommit', path, hash),
    commitDiff:   (path: string, hash: string)               => ipcRenderer.invoke('git:commitDiff', path, hash),
    commitFiles:  (path: string, hash: string)               => ipcRenderer.invoke('git:commitFiles', path, hash),
    scanRepos: (path: string, maxDepth?: number)            => ipcRenderer.invoke('git:scanRepos', path, maxDepth),
  },
  project: {
    listWorkspace:      ()                                                => ipcRenderer.invoke('project:listWorkspace'),
    createInWorkspace:  (name: string)                                    => ipcRenderer.invoke('project:createInWorkspace', name),
    loadFromPath:       (filePath: string)                                => ipcRenderer.invoke('project:loadFromPath', filePath),
    save:               (args: { project: any; filePath: string })        => ipcRenderer.invoke('project:save', args),
    saveAs:             (project: any)                                    => ipcRenderer.invoke('project:saveAs', project),
    delete:             (filePath: string)                                => ipcRenderer.invoke('project:delete', filePath),
    import:             ()                                                => ipcRenderer.invoke('project:import'),
  },
  github: {
    getToken:     ()                                                    => ipcRenderer.invoke('github:getToken'),
    setToken:     (token: string)                                       => ipcRenderer.invoke('github:setToken', token),
    detectRepo:   (repoPath: string)                                    => ipcRenderer.invoke('github:detectRepo', repoPath),
    listIssues:   (repoPath: string, state?: string)                    => ipcRenderer.invoke('github:listIssues', repoPath, state),
    getIssue:     (repoPath: string, number: number)                    => ipcRenderer.invoke('github:getIssue', repoPath, number),
    getComments:  (repoPath: string, number: number)                    => ipcRenderer.invoke('github:getComments', repoPath, number),
    addComment:   (repoPath: string, number: number, body: string)      => ipcRenderer.invoke('github:addComment', repoPath, number, body),
    updateIssue:  (repoPath: string, number: number, patch: any)        => ipcRenderer.invoke('github:updateIssue', repoPath, number, patch),
    updateComment:(repoPath: string, commentId: number, body: string)   => ipcRenderer.invoke('github:updateComment', repoPath, commentId, body),
    listLabels:          (repoPath: string)                                  => ipcRenderer.invoke('github:listLabels', repoPath),
    getNotifications:    (participating?: boolean)                           => ipcRenderer.invoke('github:getNotifications', participating),
    markNotificationRead:(threadId: string)                                  => ipcRenderer.invoke('github:markNotificationRead', threadId),
    createIssue:         (repoPath: string, payload: any)                    => ipcRenderer.invoke('github:createIssue', repoPath, payload),
    listAllRepos:        ()                                                   => ipcRenderer.invoke('github:listAllRepos'),
  },
  localIssue: {
    load:         (slug: string)                                                             => ipcRenderer.invoke('localIssue:load',         slug),
    addGroup:     (slug: string, label: string)                                              => ipcRenderer.invoke('localIssue:addGroup',     slug, label),
    renameGroup:  (slug: string, groupId: string, label: string)                             => ipcRenderer.invoke('localIssue:renameGroup',  slug, groupId, label),
    toggleGroup:  (slug: string, groupId: string)                                            => ipcRenderer.invoke('localIssue:toggleGroup',  slug, groupId),
    reorderGroups:(slug: string, order: string[])                                            => ipcRenderer.invoke('localIssue:reorderGroups',slug, order),
    deleteGroup:  (slug: string, groupId: string)                                            => ipcRenderer.invoke('localIssue:deleteGroup',  slug, groupId),
    addLista:     (slug: string, groupId: string, label: string)                             => ipcRenderer.invoke('localIssue:addLista',     slug, groupId, label),
    renameLista:  (slug: string, groupId: string, listaId: string, label: string)            => ipcRenderer.invoke('localIssue:renameLista',  slug, groupId, listaId, label),
    deleteLista:  (slug: string, groupId: string, listaId: string)                           => ipcRenderer.invoke('localIssue:deleteLista',  slug, groupId, listaId),
    createIssue:  (slug: string, groupId: string, listaId: string, data: any)               => ipcRenderer.invoke('localIssue:createIssue',  slug, groupId, listaId, data),
    updateIssue:  (slug: string, issueId: string, patch: any)                               => ipcRenderer.invoke('localIssue:updateIssue',  slug, issueId, patch),
    deleteIssue:  (slug: string, issueId: string)                                            => ipcRenderer.invoke('localIssue:deleteIssue',  slug, issueId),
    addComment:   (slug: string, issueId: string, body: string)                              => ipcRenderer.invoke('localIssue:addComment',   slug, issueId, body),
    deleteComment:(slug: string, issueId: string, commentId: string)                         => ipcRenderer.invoke('localIssue:deleteComment',slug, issueId, commentId),
    updateComment:(slug: string, issueId: string, commentId: string, body: string)           => ipcRenderer.invoke('localIssue:updateComment',slug, issueId, commentId, body),
  },
  conflict: {
    list:        (repoPath: string)                                    => ipcRenderer.invoke('conflict:list', repoPath),
    readFile:    (repoPath: string, file: string)                      => ipcRenderer.invoke('conflict:readFile', repoPath, file),
    resolveFile: (repoPath: string, file: string, content: string)     => ipcRenderer.invoke('conflict:resolveFile', repoPath, file, content),
    resolveWith: (repoPath: string, file: string, side: string)        => ipcRenderer.invoke('conflict:resolveWith', repoPath, file, side),
    abortMerge:  (repoPath: string)                                    => ipcRenderer.invoke('conflict:abortMerge', repoPath),
  },
  notes: {
    load:           (projectId: string)                                                                                            => ipcRenderer.invoke('notes:load', projectId),
    saveNotebook:   (args: { projectId: string; notebook: any; notebookOrder: string[] })                                          => ipcRenderer.invoke('notes:saveNotebook', args),
    saveNote:       (args: { projectId: string; notebookId: string; note: any; noteOrder: string[] })                              => ipcRenderer.invoke('notes:saveNote', args),
    deleteNote:     (args: { projectId: string; notebookId: string; noteId: string })                                              => ipcRenderer.invoke('notes:deleteNote', args),
    deleteNotebook: (args: { projectId: string; notebookId: string })                                                              => ipcRenderer.invoke('notes:deleteNotebook', args),
    hasPassword:    ()                                                                                                   => ipcRenderer.invoke('notes:hasPassword'),
    setPassword:    (password: string)                                                                                   => ipcRenderer.invoke('notes:setPassword', password),
    verifyPassword: (password: string)                                                                                   => ipcRenderer.invoke('notes:verifyPassword', password),
    removePassword: ()                                                                                                   => ipcRenderer.invoke('notes:removePassword'),
    encrypt:        (args: { content: string; password: string })                                                       => ipcRenderer.invoke('notes:encrypt', args),
    decrypt:        (args: { encrypted: string; password: string })                                                     => ipcRenderer.invoke('notes:decrypt', args),
  },
  backup: {
    export:     () => ipcRenderer.invoke('backup:export'),
    import:     () => ipcRenderer.invoke('backup:import'),
    openFolder: () => ipcRenderer.invoke('backup:openFolder'),
  },
  dialog: {
    openDirectory: () => ipcRenderer.invoke('dialog:openDirectory'),
  },
  shell: {
    openExternal: (url: string) => ipcRenderer.invoke('shell:openExternal', url),
  },
  app: {
    versions: process.versions as Record<string, string>,
    platform: process.platform,
  },
})
